[
  {
    "name": "LeBron James",
    "voted": "starter",
    "captain": "lebron",
    "number": 23,
    "team": "CLE",
    "position": "Forward",
    "points_per_game": 26.6,
    "assists_per_game": 8.7,
    "rebounds_per_game": 7.9,
    "true_shooting_%": 0.623,
    "win_shares": 7.9,
    "box_plus_minus": 8.7,
    "value_over_replacement_player": 5
  },
  {
    "name": "DeMarcus Cousins",
    "voted": "starter",
    "captain": "lebron",
    "number": 0,
    "team": "NOP",
    "position": "Center",
    "points_per_game": 25.2,
    "assists_per_game": 5.4,
    "rebounds_per_game": 12.9,
    "true_shooting_%": 0.583,
    "win_shares": 4.7,
    "box_plus_minus": 5.2,
    "value_over_replacement_player": 3.1
  },
  {
    "name": "Anthony Davis",
    "voted": "starter",
    "captain": "lebron",
    "number": 23,
    "team": "NOP",
    "position": "Forward",
    "points_per_game": 26.4,
    "assists_per_game": 2.6,
    "rebounds_per_game": 10.6,
    "true_shooting_%": 0.627,
    "win_shares": 8.1,
    "box_plus_minus": 4.7,
    "value_over_replacement_player": 2.7
  },
  {
    "name": "Kevin Durant",
    "voted": "starter",
    "captain": "lebron",
    "number": 35,
    "team": "GSW",
    "position": "Forward",
    "points_per_game": 25.6,
    "assists_per_game": 5.6,
    "rebounds_per_game": 6.9,
    "true_shooting_%": 0.626,
    "win_shares": 6.3,
    "box_plus_minus": 5.3,
    "value_over_replacement_player": 2.8
  },
  {
    "name": "Kyrie Irving",
    "voted": "starter",
    "captain": "lebron",
    "number": 11,
    "team": "BOS",
    "position": "Guard",
    "points_per_game": 24.9,
    "assists_per_game": 5,
    "rebounds_per_game": 3.7,
    "true_shooting_%": 0.601,
    "win_shares": 7.4,
    "box_plus_minus": 6,
    "value_over_replacement_player": 3.2
  },
  {
    "name": "LaMarcus Aldridge",
    "voted": "reserve",
    "captain": "lebron",
    "number": 12,
    "team": "SAS",
    "position": "Forward",
    "points_per_game": 22.4,
    "assists_per_game": 1.9,
    "rebounds_per_game": 8.5,
    "true_shooting_%": 0.556,
    "win_shares": 6.9,
    "box_plus_minus": 2.2,
    "value_over_replacement_player": 1.8
  },
  {
    "name": "Bradley Beal",
    "voted": "reserve",
    "captain": "lebron",
    "number": 3,
    "team": "WAS",
    "position": "Guard",
    "points_per_game": 23.8,
    "assists_per_game": 3.9,
    "rebounds_per_game": 4.4,
    "true_shooting_%": 0.568,
    "win_shares": 5,
    "box_plus_minus": 2.1,
    "value_over_replacement_player": 1.9
  },
  {
    "name": "Andre Drummond",
    "voted": "reserve",
    "captain": "lebron",
    "number": 0,
    "team": "DET",
    "position": "Center",
    "points_per_game": 14.8,
    "assists_per_game": 3.9,
    "rebounds_per_game": 15.3,
    "true_shooting_%": 0.574,
    "win_shares": 6.6,
    "box_plus_minus": 7.3,
    "value_over_replacement_player": 3.7
  },
  {
    "name": "Paul George",
    "voted": "reserve",
    "captain": "lebron",
    "number": 13,
    "team": "OKC",
    "position": "Forward",
    "points_per_game": 21.3,
    "assists_per_game": 2.9,
    "rebounds_per_game": 5.5,
    "true_shooting_%": 0.579,
    "win_shares": 5.7,
    "box_plus_minus": 2.7,
    "value_over_replacement_player": 2.1
  },
  {
    "name": "Kevin Love",
    "voted": "reserve",
    "captain": "lebron",
    "number": 0,
    "team": "CLE",
    "position": "Forward",
    "points_per_game": 17.9,
    "assists_per_game": 1.6,
    "rebounds_per_game": 9.4,
    "true_shooting_%": 0.613,
    "win_shares": 5.3,
    "box_plus_minus": 1.1,
    "value_over_replacement_player": 1.1
  },
  {
    "name": "Victor Oladipo",
    "voted": "reserve",
    "captain": "lebron",
    "number": 4,
    "team": "IND",
    "position": "Guard",
    "points_per_game": 23.9,
    "assists_per_game": 4.1,
    "rebounds_per_game": 5.2,
    "true_shooting_%": 0.595,
    "win_shares": 5.4,
    "box_plus_minus": 4.3,
    "value_over_replacement_player": 2.6
  },
  {
    "name": "Kristaps Porzingis",
    "voted": "reserve",
    "captain": "lebron",
    "number": 6,
    "team": "NYK",
    "position": "Forward",
    "points_per_game": 23.1,
    "assists_per_game": 1.3,
    "rebounds_per_game": 6.6,
    "true_shooting_%": 0.539,
    "win_shares": 3.5,
    "box_plus_minus": -0.3,
    "value_over_replacement_player": 0.6
  },
  {
    "name": "John Wall",
    "voted": "reserve",
    "captain": "lebron",
    "number": 2,
    "team": "WAS",
    "position": "Guard",
    "points_per_game": 19.4,
    "assists_per_game": 9.3,
    "rebounds_per_game": 3.6,
    "true_shooting_%": 0.511,
    "win_shares": 2.6,
    "box_plus_minus": 1.6,
    "value_over_replacement_player": 1.2
  },
  {
    "name": "Russell Westbrook",
    "voted": "reserve",
    "captain": "lebron",
    "number": 0,
    "team": "OKC",
    "position": "Guard",
    "points_per_game": 25.5,
    "assists_per_game": 10.1,
    "rebounds_per_game": 9.4,
    "true_shooting_%": 0.516,
    "win_shares": 6.7,
    "box_plus_minus": 8.7,
    "value_over_replacement_player": 4.9
  },
  {
    "name": "Giannis Antetokounmkpo",
    "voted": "starter",
    "captain": "stephen",
    "number": 34,
    "team": "MIL",
    "position": "Forward",
    "points_per_game": 28.5,
    "assists_per_game": 4.7,
    "rebounds_per_game": 10.3,
    "true_shooting_%": 0.618,
    "win_shares": 8.8,
    "box_plus_minus": 7.3,
    "value_over_replacement_player": 4
  },
  {
    "name": "Stephen Curry",
    "voted": "starter",
    "captain": "stephen",
    "number": 30,
    "team": "GSW",
    "position": "Guard",
    "points_per_game": 27.7,
    "assists_per_game": 6.5,
    "rebounds_per_game": 5.1,
    "true_shooting_%": 0.675,
    "win_shares": 7.1,
    "box_plus_minus": 8.8,
    "value_over_replacement_player": 3.3
  },
  {
    "name": "DeMar DeRozan",
    "voted": "starter",
    "captain": "stephen",
    "number": 10,
    "team": "TOR",
    "position": "Guard",
    "points_per_game": 24.4,
    "assists_per_game": 5.2,
    "rebounds_per_game": 4.1,
    "true_shooting_%": 0.566,
    "win_shares": 6.6,
    "box_plus_minus": 2.6,
    "value_over_replacement_player": 2
  },
  {
    "name": "Joel Embiid",
    "voted": "starter",
    "captain": "stephen",
    "number": 21,
    "team": "PHI",
    "position": "Center",
    "points_per_game": 23.8,
    "assists_per_game": 3.3,
    "rebounds_per_game": 11,
    "true_shooting_%": 0.584,
    "win_shares": 3.8,
    "box_plus_minus": 2.6,
    "value_over_replacement_player": 1.4
  },
  {
    "name": "James Harden",
    "voted": "starter",
    "captain": "stephen",
    "number": 13,
    "team": "HOU",
    "position": "Guard",
    "points_per_game": 31.6,
    "assists_per_game": 9.1,
    "rebounds_per_game": 5,
    "true_shooting_%": 0.622,
    "win_shares": 9.3,
    "box_plus_minus": 10.6,
    "value_over_replacement_player": 4.8
  },
  {
    "name": "Jimmy Butler",
    "voted": "reserve",
    "captain": "stephen",
    "number": 23,
    "team": "MIN",
    "position": "Guard",
    "points_per_game": 21.8,
    "assists_per_game": 5,
    "rebounds_per_game": 5.4,
    "true_shooting_%": 0.589,
    "win_shares": 7.4,
    "box_plus_minus": 5,
    "value_over_replacement_player": 3.1
  },
  {
    "name": "Draymond Green",
    "voted": "reserve",
    "captain": "stephen",
    "number": 23,
    "team": "GSW",
    "position": "Forward",
    "points_per_game": 11.3,
    "assists_per_game": 7.3,
    "rebounds_per_game": 7.9,
    "true_shooting_%": 0.567,
    "win_shares": 4.3,
    "box_plus_minus": 3.8,
    "value_over_replacement_player": 2.1
  },
  {
    "name": "Al Horford",
    "voted": "reserve",
    "captain": "stephen",
    "number": 42,
    "team": "BOS",
    "position": "Center",
    "points_per_game": 13.3,
    "assists_per_game": 5.3,
    "rebounds_per_game": 7.9,
    "true_shooting_%": 0.588,
    "win_shares": 6,
    "box_plus_minus": 5.1,
    "value_over_replacement_player": 2.7
  },
  {
    "name": "Damian Lillard",
    "voted": "reserve",
    "captain": "stephen",
    "number": 0,
    "team": "POR",
    "position": "Guard",
    "points_per_game": 25.2,
    "assists_per_game": 6.5,
    "rebounds_per_game": 4.7,
    "true_shooting_%": 0.591,
    "win_shares": 6.8,
    "box_plus_minus": 5.7,
    "value_over_replacement_player": 3.1
  },
  {
    "name": "Kyle Lowry",
    "voted": "reserve",
    "captain": "stephen",
    "number": 7,
    "team": "TOR",
    "position": "Guard",
    "points_per_game": 16.4,
    "assists_per_game": 6.6,
    "rebounds_per_game": 6,
    "true_shooting_%": 0.583,
    "win_shares": 5.4,
    "box_plus_minus": 5,
    "value_over_replacement_player": 2.7
  },
  {
    "name": "Klay Thompson",
    "voted": "reserve",
    "captain": "stephen",
    "number": 11,
    "team": "GSW",
    "position": "Guard",
    "points_per_game": 20.3,
    "assists_per_game": 2.6,
    "rebounds_per_game": 4,
    "true_shooting_%": 0.606,
    "win_shares": 3.8,
    "box_plus_minus": -0.1,
    "value_over_replacement_player": 0.8
  },
  {
    "name": "Karl-Anthony Towns",
    "voted": "reserve",
    "captain": "stephen",
    "number": 32,
    "team": "MIN",
    "position": "Center",
    "points_per_game": 19.8,
    "assists_per_game": 2.3,
    "rebounds_per_game": 12.1,
    "true_shooting_%": 0.636,
    "win_shares": 8.5,
    "box_plus_minus": 5,
    "value_over_replacement_player": 3.4
  }
]